spring.application.name=ms_transaction

# ========================
# DATASOURCE - PostgreSQL
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_transaction
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ========================
# JWT - MISMA CONFIGURACION QUE ms_user  ? SIN TILDES
# ========================
jwt.secret=UE1aTnpNMFF6TlRneU5UZ3lOek13TURJeE56QXhNekkxT0RBek16Y3pPREUwTnpJMk5Ea3pOVEk0T0RFM05UUTJOelkzT0RJMU56Y3hPVE14TnpZME1qUXdNREF3TURBd01EQXdNREF3TURBd01EQT0=

# ========================
# SERVER
# ========================
server.port=8082

# ========================
# ACTUATOR
# ========================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ========================
# LOGGING (Para debug)
# ========================
logging.level.org.springframework.security=DEBUG
logging.level.com.project=DEBUG